### ISSUE TITLE
Transliteration 

### ISSUE THREAD

**Issue by aneesh1122** [therealbush/translator#5]
When `println(translation.pronunciation)` is used it uses the translated text to transliterate. Is it possible to use the pronunciation command for the original text?

**Comment by therealbush** [comment]
I don't think so. this is a limitation of Google translate's api.

**Comment by aneesh1122** [comment]
> I don't think so. this is a limitation of Google translate's api.

Okay. Thanks for you reply

**Comment by therealbush** [comment]
I was incorrect. see https://github.com/therealbush/translator/pull/7
