### ISSUE TITLE
Kotlin 1.9.23 compatibility issue 

### ISSUE THREAD

**Issue by Ekagra** [therealbush/translator#8]
I'm trying to implement the com.github.therealbush:translator:1.1.1 library in my project. However, I am encountering the following error when I try to build the project with translator dependency for _kotlinx.serialization.Serializable_: `Your current Kotlin version is 1.9.23, while kotlinx.serialization core runtime 1.7.3 requires at least Kotlin 2.0.0-RC1. Please update your Kotlin compiler and IDE plugin.`

Here are the details of my environment:

Kotlin version: 1.9.23
Ktor version: 3.0.0-beta-1

**Comment by therealbush** [comment]
As your error states, kotlinx.serialization requires Kotlin 2.0.0 and you are on Kotlin 1.9.23. Consider updating your Kotlin version.
